let SchoolList = [
    {id:1, name:'St. Joseph', location:'Mumbai'},
    {id:2, name:'St. Mary', location:'Pune'},
    {id:3, name:'St. Xavier', location:'Delhi'},
    {id:4, name:'St. Paul', location:'Bangalore'},
    {id:5, name:'St. John', location:'Chennai'},
    {id:6, name:'St. Peter', location:'Kolkata'},
    {id:7, name:'St. Andrew', location:'Hyderabad'},
    {id:8, name:'St. Jude', location:'Ahmedabad'},
    {id:9, name:'St. Thomas', location:'Jaipur'},
    {id:10, name:'St. Luke', location:'Lucknow'},
    {id:11, name:'St. Matthew', location:'Kanpur'},
    {id:12, name:'St. Mark', location:'Nagpur'},
    {id:13, name:'St. Timothy', location:'Indore'},
    {id:14, name:'St. Titus', location:'Thane'},
    {id:15, name:'St. Silas', location:'Nashik'},
    {id:16, name:'St. Simon', location:'Surat'},
    {id:17, name:'St. Stephen', location:'Vadodara'},
    {id:18, name:'St. Thaddeus', location:'Bhopal'},
    {id:19, name:'St. Thomas', location:'Patna'},
    {id:20, name:'St. Titus', location:'Ludhiana'},
    {id:21, name:'St. Timothy', location:'Agra'},
    {id:22, name:'St. Titus', location:'Varanasi'},
    {id:23, name:'St. Silas', location:'Meerut'},
    {id:24, name:'St. Simon', location:'Allahabad'},
    {id:25, name:'St. Stephen', location:'Ranchi'},
    {id:26, name:'St. Thaddeus', location:'Jabalpur'},
    {id:27, name:'St. Thomas', location:'Srinagar'},
    {id:28, name:'St. Titus', location:'Shimla'},
    {id:29, name:'St. Timothy', location:'Gangtok'},
    {id:30, name:'St. Titus', location:'Kohima'}

]
export default SchoolList;